" ---] Map
inoremap jj <ESC>

" ---] Settings
set mouse=a              " Enable mouse
set encoding=utf-8
set t_Co=256
set term=xterm-256color
set termencoding=utf-8
set number               " Show line numbers
set ts=2                 " Tabs = 2 spaces
set autoindent           " Autoindent tabs
set smartindent
set expandtab
set shiftwidth=2      
set showmatch
set incsearch            " Shows the match while typing
set hlsearch
set ignorecase
set smartcase

" --] Theme
set background=dark
colorscheme PaperColor

" --] Plugins
set nocompatible " Required
filetype off     " Required

set rtp+=~/.vim/bundle/Vundle.vim " Set runtime path to include Vundle & initialize
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'    " Required
Plugin 'cespare/vim-toml'        " Toml syntax
Plugin 'ekalinin/Dockerfile.vim' " Dockerfile syntax
Plugin 'jiangmiao/auto-pairs'    " Insert or delete brackets, quotes, etc. in a pair
Plugin 'rust-lang/rust.vim'      " Rust syntax
Plugin 'fatih/vim-go'            " Go syntax & Auto format

call vundle#end()         " Required
filetype plugin indent on " Required
