# Golang
export GOPATH=$HOME/.go
export PATH=$PATH:/usr/local/opt/go/bin:$GOPATH/bin

# Rust
export PATH=$HOME/.cargo/bin:$PATH

# pyenv
eval "$(pyenv init -)"

# HIST
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000
HIST_STAMPS="yyyy-mm-dd"

# Zsh Settings
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

CASE_SENSITIVE="true"
ENABLE_CORRECTION="true"

plugins=(
	git
  debian
  encode64
)

source $ZSH/oh-my-zsh.sh

# Aliases
alias ll='ls -alF'
