# Path
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Golang
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/.golang
export PATH=$PATH:$GOPATH/bin

# Rust
export PATH=$HOME/.cargo/bin:$PATH

# 256 Colors
if [ "$TERM" = "xterm" ] || [ "$TERM" = "xterm-256color" ]; then
  export TERM=xterm-256color
  export HAS_256_COLORS=yes
fi
if [ "$TERM" = "screen" ] && [ "$HAS_256_COLORS" = "yes" ]; then
  export TERM=screen-256color
fi

# Locale
export LANG=en_US.UTF-8

# HIST
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000
HIST_STAMPS="yyyy-mm-dd"

# Zsh Settings
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="haccer"

CASE_SENSITIVE="true"
ENABLE_CORRECTION="true"

plugins=(
  debian
  encode64  
)

source $ZSH/oh-my-zsh.sh

# Aliases
alias ll='ls -alF'
